export const ACTION_INPUT_URL = 'TRETTON37/ACTION_INPUT_URL';
export const ACTION_CREATE_URL = 'TRETTON37/ACTION_CREATE_URL';
export const ACTION_CREATE_URL_OK = 'TRETTON37/ACTION_CREATE_URL_OK';
export const ACTION_CREATE_URL_FAIL = 'TRETTON37/ACTION_CREATE_URL_FAIL';
export const ACTION_CREATE_URL_CANCEL = 'TRETTON37/ACTION_CREATE_URL_CANCEL';
export const ACTION_CREATE_URL_TIMEOUT = 'TRETTON37/ACTION_CREATE_URL_TIMEOUT';